- name: Installing some applications in Ubuntu
  hosts: docker_containers  # this is defined in inventory.ini file
  become: yes  # that is used to execute the tasks with root permissions

  tasks:
    - name: Install curl
      apt:
        name: curl
        state: present
        update_cache: yes

    - name: Install PostgreSQL
      apt:
        name: postgresql
        state: present
